NAME=memkeys-build
TAG=latest

all:
	docker build --force-rm -t $(NAME):$(TAG) .

nocache:
	docker build --force-rm --no-cache -t $(NAME):$(TAG) .

extractbinary:
	docker run -it --rm -v $(shell pwd)/src:/local memkeys-build:latest cp /memkeys/src/memkeys /local/memkeys
